name: Docker Build and Save

on:
  push:
    tags:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t your-image-name .

    - name: Save Docker Image as Tar
      run: docker save your-image-name -o image.tar

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: image.tar